HEADER_VARS = {
                'HST_WFC3': ['TARGNAME','FILENAME','RA_TARG','DEC_TARG','FILETYPE','DATE-OBS','TIME-OBS','EXPTIME','OBSTYPE','OBSMODE','FILTER','PHOTFLAM','PHOTFNU','PHOTZPT','PHOTPLAM','PHOTBW','CCDGAIN']
        }

STR_COLS = {}

PIXSCALE = {
    'HST_WFC3': 'D002SCAL'
}

EXPTIME = {
    'HST_WFC3': 'EXPTIME'
}

VEGA_ZEROPTS = {
    'F105W':25.4523,
    'F125W':25.1439
}

GAIN = {
    'HST_WFC3': 'CCDGAIN'
    #2.5
}
#test
